u_a_s/enroll/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('signup/',views.sign_up),
    path('login/',views.user_login),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.user_logout),
    path('changepass/',views.user_change_pass,name='changepass'),
    path('changepass2/',views.user_change_pass2,name='changepass2'),
    path('userdetail/<int:id>',views.user_detail,name='userdetail'),
    path('dashboard/',views.user_dashboard,name='dashboard'),
]

u_a_s/u_a_s/urls.py
from django.contrib import admin
from django.urls import path,include
from enroll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enroll/', include('enroll.urls')),
]

u_a_s/enroll/models.py
from unicodedata import name
from django.db import models

class blog(models.Model):
    title = models.CharField(max_length=50)
    desc = models.CharField(max_length=100)

u_a_s/enroll/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class signupform(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password (again)',widget=forms.PasswordInput)
    class Meta:
        model=User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}
        
class edituserprofileform(UserChangeForm):
    password = None
    class Meta:
        model=User
        fields = ['username','first_name','last_name','email','date_joined','last_login']
        labels = {'email':'Email'}

class editadminprofileform(UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'

u_a_s/enroll/views.py
from urllib import request
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import signupform,edituserprofileform,editadminprofileform
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm,SetPasswordForm,UserChangeForm
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.contrib.auth.models import User

# Create your views here.
# signup view function
def sign_up(request):
    if request.method == "POST":
        fm = signupform(request.POST)
        if fm.is_valid():
            fm.save()
            messages.success(request,'Account created successfully')
        
    else:
        fm = signupform()
    return render(request,'enroll/signup.html',{'form':fm})

# login view function
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            frm = AuthenticationForm(request=request,data=request.POST)
            if frm.is_valid():
                uname = frm.cleaned_data['username']
                upass = frm.cleaned_data['password']
                users = authenticate(username = uname,password = upass)
                if users: 
                    login(request,users)
                    # return HttpResponseRedirect('/enroll/profile/')
                    return HttpResponseRedirect('/enroll/dashboard/')
        else:
            frm =AuthenticationForm()
        return render(request,'enroll/userlogin.html',{'form':frm})
    else:
        # return HttpResponseRedirect('/enroll/profile')
        return HttpResponseRedirect('/enroll/dashboard')


# profile view
def profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if request.user.is_superuser == True:
                fm = editadminprofileform(request.POST,instance=request.user)
                users = User.objects.all()
            else:
                fm =edituserprofileform(request.POST,instance = request.user)
                users=None
            if fm.is_valid():
                messages.success(request,'Profile updated..!!')
                fm.save()
        else:
            if request.user.is_superuser == True:
                fm = editadminprofileform(request.POST,instance=request.user)
                users = User.objects.all()
            else:
                fm =edituserprofileform(request.POST,instance = request.user)
                users=None
        return render(request,'enroll/profile.html',{'name':request.user,'form':fm,'users':users})
    else:
        return HttpResponseRedirect('/enroll/login')

#  logout user 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/enroll/login/')


# change password with old password
def user_change_pass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            frm=PasswordChangeForm(user=request.user,data=request.POST)
            # print(frm)
            if frm.is_valid():
                frm.save()
                # to update session otherwise you redirected to the login page because of session expired
                update_session_auth_hash(request,frm.user)
                messages.success(request,'Password Changed successfully')
                return HttpResponseRedirect('/enroll/profile')
        frm=PasswordChangeForm(user=request.user)
        return render(request,'enroll/changepass.html',{'form':frm})
    else:
        return HttpResponseRedirect('/enroll/login')


# change password without old password
def user_change_pass2(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            frm=SetPasswordForm(user=request.user,data=request.POST)
            # print(frm)
            if frm.is_valid():
                frm.save()
                # to update session otherwise you redirected to the login page because of session expired
                update_session_auth_hash(request,frm.user)
                messages.success(request,'Password Changed successfully')
                return HttpResponseRedirect('/enroll/profile')
        frm=SetPasswordForm(user=request.user)
        return render(request,'enroll/changepass.html',{'form':frm})
    else:
        return HttpResponseRedirect('/enroll/login')


def user_detail(request,id):
    if request.user.is_authenticated:
        pi = User.objects.get(pk=id)
        fm = editadminprofileform(instance=pi)
        return render(request,'enroll/userdetail.html',{'form':fm})
    else:
        return HttpResponseRedirect('/enroll/login/')



def user_dashboard(request):
    if request.user.is_authenticated:
        return render(request,'enroll/dashboard.html')
        # return HttpResponseRedirect('/enroll/dashboard')
    else:
        return HttpResponseRedirect('/enroll/login')

u_a_s/enroll/templates/enroll/changepass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        
            {% for error in form.non_field_errors %}
                <p class="err">{{error}}</p>
            {% endfor %}
        {% endif %}

        {% for fm in form %}
            <div>
                {{fm.label_tag}} {{fm}} <span class="errorlist">{{fm.errors|striptags}}</span><br><br>
            </div>
        {% endfor %}
        <!-- {{form.as_p}} -->
        <input type="submit" value="change password">
    </form>
    <!-- {% if messages %}
        {% for message in messages %}
            <span {% if message.tags %} class="alert-{{message.tags}} {% endif %}"> {{ message }}</span>
        {% endfor %}
    {% endif %} -->
</body>
</html>

u_a_s/enroll/templates/enroll/changepass2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        
            {% for error in form.non_field_errors %}
                <p class="err">{{error}}</p>
            {% endfor %}
        {% endif %}

        {% for fm in form %}
            <div>
                {{fm.label_tag}} {{fm}} <span class="errorlist">{{fm.errors|striptags}}</span><br><br>
            </div>
        {% endfor %}
        <!-- {{form.as_p}} -->
        <input type="submit" value="change password">
    </form>
    <!-- {% if messages %}
        {% for message in messages %}
            <span {% if message.tags %} class="alert-{{message.tags}} {% endif %}"> {{ message }}</span>
        {% endfor %}
    {% endif %} -->
</body>
</html>

u_a_s/enroll/templates/enroll/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Dashboard</h1>
    <h3>welcome {{name}}</h3>
    {% if perms.enroll.add_blog %}
        <input type="button" value="Add"><br><br>
    {% else %}
        <h3>No Add permission</h3>
    {% endif %}
    
    {% if perms.enroll.delete_blog %}
        <input type="button" value="Delete"><br><br>
    {% else %}
        <h3>No Delete permission</h3>
    {% endif %}
    
    <a href="/enroll/logout/">Logout</a>
</body>
</html>

u_a_s/enroll/templates/enroll/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome {{name}} to Profile</h1>
    {% for user in users %}
        <a href="/enroll/userdetail/{{ user.id }}">{{user.username}}</a>
    {% endfor %}

    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="err">{{error}}</p>
            {% endfor %}
        {% endif %}


        {% for fm in form %}
        <div>
            {{fm.label_tag}} {{fm}} <span class="errorlist">{{fm.errors|striptags}}</span> <br><br>
        </div>
        {% endfor %}
        
        <input type="submit" value="Add">
        <a href="/enroll/signup">Click here to SignUp</a>
    </form>




    <a href="/enroll/logout/">Logout</a>
    <a href="/enroll/changepass/">Change Password</a>
    <a href="/enroll/changepass2/">Change Password 2</a>


    {% if messages %}
        {% for message in messages %}
            <span {% if message.tags %} class="alert-{{message.tags}} {% endif %}"> {{ message }}</span>
        {% endfor %}
    {% endif %}

    
</body>
</html>

u_a_s/enroll/templates/enroll/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Regestration</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
</head>
<body>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div>
            {{fm.label_tag}} {{fm}} <span class="errorlist"><span>{{fm.errors|striptags}}</span></span><br>
        </div>
        {% endfor %}
        <input type="submit" value="submit">
        
    </form>

    {% if messages %}
        {% for message in messages %}
            <span {% if message.tags %} class="alert-{{message.tags}} {% endif %}"> {{ message }}</span>
        {% endfor %}
    {% endif %}
    <a href="/enroll/login">Login Here</a>
</body>
</html>

u_a_s/enroll/templates/enroll/userdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {{form.as_p}}
    </form>
    <a href="{% url 'profile' %}">Profile</a>
</body>
</html>

u_a_s/enroll/templates/enroll/userlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <style>
        .err{
            color: red;
        }
    </style>
        
</head>
<body>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        
            {% for error in form.non_field_errors %}
                <p class="err">{{error}}</p>
            {% endfor %}
        {% endif %}


        {% for fm in form %}
        <div>
            {{fm.label_tag}} {{fm}} <span class="errorlist">{{fm.errors|striptags}}</span> <br><br>
        </div>
        {% endfor %}
        
        <input type="submit" value="login">
        <a href="/enroll/signup">Click here to SignUp</a>
    </form>
     <!-- {% if messages %}
        {% for message in messages %}
            <span {% if message.tags %} class="alert-{{message.tags}} {% endif %}"> {{ message }}</span>
        {% endfor %}
    {% endif %} -->
</body>
</html>